# Generated by Django 5.1.7 on 2025-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=10000)),
                ('nbrvictoryF', models.IntegerField(default=0)),
                ('nbrvictoryB', models.IntegerField(default=0)),
                ('nbrdefeatF', models.IntegerField(default=0)),
                ('nbrdefeatB', models.IntegerField(default=0)),
                ('nbrdrawF', models.IntegerField(default=0)),
                ('nbrdrawB', models.IntegerField(default=0)),
                ('numbercase', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
