# Generated by Django 5.1.7 on 2025-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splashmem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pourcentage',
            field=models.FloatField(default=0.0),
        ),
    ]
